apiVersion: apps/v1
kind: Deployment
metadata:
  name: lens-lounge-deploy
spec:
  selector:
    matchLabels:
      app:  lens-lounge-deploy
  template:
    metadata:
      labels:
        app: lens-lounge-deploy
    spec:
      containers:
        - name: lens-lounge-deploy
          image: sergehall/lens-lounge
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 5000
