apiVersion: apps/v1
kind: Deployment
metadata:
  name: lens-lounge
  labels:
    app:  lens-lounge
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  lens-lounge
  template:
    metadata:
      name: lens-lounge
      labels:
        app:  lens-lounge
    spec:
      containers:
        - name: lens-lounge
          image: sergehall/lens-lounge
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always