apiVersion: v1
kind: Service
metadata:
  name: lens-lounge-deploy
spec:
  selector:
    app: lens-lounge-deploy  # <--- This is the label that the service will select
  ports:
    - protocol: TCP
      port: 3000  # <--- This is the port that the service will be listening on
      targetPort: 5000 # <--- This is the port that the container is listening on
  type: LoadBalancer
  